#!/bin/bash

pre_upgrade() {
    # Remove some files (possible leftovers from other packages).

    local remove=(
       /usr/share/encryptos/encryptos-icon.png
       /usr/share/encryptos/encryptos-logo.png
       /usr/share/encryptos/splash.png
       /usr/share/encryptos/encryptos-logo-e.png
       /usr/share/encryptos/encryptos-icon-fade.png
       /usr/share/encryptos/encryptos-icon-E.png
       /usr/share/encryptos/encryptos-wallpaper.png
       /usr/share/encryptos/backgrounds/encryptos-wallpaper.png
    )
    local xx removed=()

    # Test if the files to be removed really exist.
    for xx in "${remove[@]}" ; do
        test -r $xx && removed+=($xx)
    done

    # Now remove the ones that exist.
    if [ -n "$removed" ] ; then
        echo "Removing existing files:" >&2
        for xx in "${removed[@]}" ; do
            echo "    $xx" >&2
            rm -f $xx
        done
    fi
}

pre_install() {
    pre_upgrade
}